CREATE TABLE workout (
	id SERIAL PRIMARY KEY,
	type VARCHAR NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	duration INT NOT NULL,
	calories_burned INT NOT NULL,
	workload INT NOT NULL,
	description VARCHAR
);

CREATE TABLE meal (
	id SERIAL PRIMARY KEY,
	type VARCHAR NOT NULL,
	calories INT NOT NULL,
	protein INT NOT NULL,
	carbs INT NOT NULL,
	fat INT NOT NULL,
	description VARCHAR,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
