version: "3.9"

services:
  api:
    build:
      context: ./life-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080" # Expose Go API on localhost:8080
    environment:
      - DB_URL=postgres://postgres:postgres@life-db/life?sslmode=disable
    depends_on:
      - life-db

  life-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: life
    ports:
      - "5433:5432"

  migrate:
    image: migrate/migrate:latest
    restart: on-failure
    volumes:
      - ./life-server/db/migrations/:/db
    depends_on:
      - life-db
    command:
      ["-path", "/db" ,"-database", "postgres://postgres:postgres@life-db/life?sslmode=disable", "up"]
