version: "3.9"

services:
  postgresdb:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: life
    ports:
      - "5433:5432" # Expose PostgreSQL on localhost:5432
