// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

type Meal struct {
	ID          int64   `json:"id"`
	Username    string  `json:"username"`
	Type        string  `json:"type"`
	Calories    int64   `json:"calories"`
	Protein     int64   `json:"protein"`
	Carbs       int64   `json:"carbs"`
	Fat         int64   `json:"fat"`
	Description *string `json:"description"`
	Date        string  `json:"date"`
}

type Workout struct {
	ID             int64   `json:"id"`
	Username       string  `json:"username"`
	Type           string  `json:"type"`
	CreatedAt      string  `json:"created_at"`
	Duration       int64   `json:"duration"`
	CaloriesBurned int64   `json:"calories_burned"`
	Workload       int64   `json:"workload"`
	Description    *string `json:"description"`
}
