// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workouts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkout = `-- name: CreateWorkout :one
INSERT INTO workout (type, username, duration, calories_burned, workload, description)
	VALUES ($1, $2, $3, $4, $5, $6) 
	RETURNING id, username, type, created_at, duration, calories_burned, workload, description
`

type CreateWorkoutParams struct {
	Type           string  `json:"type"`
	Username       string  `json:"username"`
	Duration       int32   `json:"duration"`
	CaloriesBurned int32   `json:"calories_burned"`
	Workload       int32   `json:"workload"`
	Description    *string `json:"description"`
}

func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error) {
	row := q.db.QueryRow(ctx, createWorkout,
		arg.Type,
		arg.Username,
		arg.Duration,
		arg.CaloriesBurned,
		arg.Workload,
		arg.Description,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Type,
		&i.CreatedAt,
		&i.Duration,
		&i.CaloriesBurned,
		&i.Workload,
		&i.Description,
	)
	return i, err
}

const getAllWorkouts = `-- name: GetAllWorkouts :many
SELECT id, username, type, created_at, duration, calories_burned, workload, description FROM workout WHERE username = $1
`

func (q *Queries) GetAllWorkouts(ctx context.Context, username string) ([]Workout, error) {
	rows, err := q.db.Query(ctx, getAllWorkouts, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Type,
			&i.CreatedAt,
			&i.Duration,
			&i.CaloriesBurned,
			&i.Workload,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkoutsByType = `-- name: GetWorkoutsByType :many
SELECT id, username, type, created_at, duration, calories_burned, workload, description FROM workout WHERE username = $1 AND type = $2
`

type GetWorkoutsByTypeParams struct {
	Username string `json:"username"`
	Type     string `json:"type"`
}

func (q *Queries) GetWorkoutsByType(ctx context.Context, arg GetWorkoutsByTypeParams) ([]Workout, error) {
	rows, err := q.db.Query(ctx, getWorkoutsByType, arg.Username, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Type,
			&i.CreatedAt,
			&i.Duration,
			&i.CaloriesBurned,
			&i.Workload,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkoutsFromDateRange = `-- name: GetWorkoutsFromDateRange :many
SELECT id, username, type, created_at, duration, calories_burned, workload, description FROM workout WHERE username = $1 AND created_at BETWEEN $2 AND $3
`

type GetWorkoutsFromDateRangeParams struct {
	Username    string           `json:"username"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	CreatedAt_2 pgtype.Timestamp `json:"created_at_2"`
}

func (q *Queries) GetWorkoutsFromDateRange(ctx context.Context, arg GetWorkoutsFromDateRangeParams) ([]Workout, error) {
	rows, err := q.db.Query(ctx, getWorkoutsFromDateRange, arg.Username, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Type,
			&i.CreatedAt,
			&i.Duration,
			&i.CaloriesBurned,
			&i.Workload,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
