---
name: Publish Docker Image

on:
  push:
   branches: main

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to docker hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN}}

      - name: Extra meta for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with: 
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Trigger Railway deployment
        run: |
          curl -X POST https://api.railway.app/v1/project/419424c8-fc49-46d8-a29d-b346e3a83a9b/deploy \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
          -d '{
            "dockerImage": "${{ env.IMAGE_NAME }}:${{ github.sha }}"
          }'
